#!/usr/bin/env bash
#' Get the x86-64 Microarchitecture Level on the Current Machine
#'
#' Queries the CPU information to infer which level of x86-64
#' microarchitecture is supported by the CPU on the current machine,
#' i.e. x86-64-v1, x86-64-v2, x86-64-v3, or x86-64-v4.
#'
#' Usage:
#' x86-64-level [options] [-]
#'
#' Options:
#'   --help            Show this help
#'   --version         Show the version of this tool
#'   --verbose         Explain the identified level
#'   --assert=<level>  Assert that CPU supports x86-64-v<level>,
#'                     exiting with code 0 if supported, otherwise 1
#'   -                 Read the CPU information from the standard
#'                     input, instead of from /proc/cpuinfo
#'
#' Examples:
#' $ x86-64-level
#' 2
#'
#' $ level=$(x86-64-level)
#' $ echo "x86-64-v${level}"
#' x86-64-v2
#'
#' $ x86-64-level --verbose
#' Identified x86-64-v2, because x86-64-v3 requires 'avx2', 'bmi2',
#' and 'fma', which are not supported by this CPU [AMD E2-3800 APU
#' with Radeon(TM) HD Graphics]
#' 2
#'
#' $ cat /proc/cpuinfo | x86-64-level -
#' 2
#'
#' $ x86-64-level --assert=2
#' $ echo $?
#' 0
#'
#' $ x86-64-level --assert=3
#' The CPU [AMD E2-3800 APU with Radeon(TM) HD Graphics] on this host
#' ('dev2') supports x86-64-v2, which is less than the required
#' x86-64-v3
#' $ echo $?
#' 1
#'
#' Version: 0.2.2-9015
#' License: CC BY-SA 4.0
#' Source code: https://github.com/HenrikBengtsson/x86-64-level
#'
#' Authors:
#' * Henrik Bengtsson (expanded on Gilles' implementation [2])
#' * StackExchange user 'Gilles'
#'   <https://stackexchange.com/users/164368/>
#' * StackExchange user 'gioele'
#'   <https://unix.stackexchange.com/users/14861/>
#'
#' References:
#' [1] https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels
#' [2] https://unix.stackexchange.com/a/631320

#---------------------------------------------------------------------
# CLI functions
#---------------------------------------------------------------------
help() {
    grep "^#'" "$0" | sed -E "s/^#' ?//"
}

version() {
    grep "^#' Version:" "$0" | sed 's/.* //'
}


#---------------------------------------------------------------------
# CPU functions
#---------------------------------------------------------------------
## The file holding the CPU information.  The environment variable is
## used for testing only, and is not part of the public interface
cpuinfo=${X86_64_LEVEL_CPUINFO:-/proc/cpuinfo}

## The CPU information read, the CPU flags parsed from it, and the
## x86-64 level inferred from those flags
data=
flags=
level=0

read_input() {
    if [[ -z ${data} ]]; then
        if ${stdin}; then
            data=$(< /dev/stdin)
        else
            if [[ ! -f ${cpuinfo} ]]; then
                echo >&2 "ERROR: No such file: ${cpuinfo} (this tool requires Linux)"
                exit 1
            fi
            data=$(< "${cpuinfo}")
        fi
        if [[ -z ${data} ]]; then
            echo >&2 "ERROR: Input data is empty"
            exit 1
        fi
    fi
}

get_cpu_name() {
    local bfr
    local name
    bfr=$(grep -E "^model name[[:space:]]*:" <<< "${data}")
    name=$(echo "${bfr}" | head -n 1)
    name="${name#model name*:}"
    echo "${name## }"
}


get_cpu_flags() {
    local bfr
    bfr=$(grep "^flags[[:space:]]*:" <<< "${data}" | head -n 1)
    bfr="${bfr#*:}"
    bfr="${bfr## }"
    if [[ ! ${bfr} =~ [^[:space:]] ]]; then
        echo >&2 "ERROR: No CPU 'flags' entry in the input data"
        exit 1
    fi
    if grep -v -q -E "^[[:lower:][:digit:]_ ]+$" <<< "${bfr}"; then
        echo >&2 "ERROR: Cannot reliably infer the CPU x86-64 level, because the format of the CPU flags comprise of other symbols than only lower-case letters, digits, and underscores: '${bfr}'"
        exit 1
    fi
    echo "${bfr}"
}


validate_cpu_flags() {
    read_input
    get_cpu_flags > /dev/null
}


## Reports on the identified level, with the CPU name, if known
explain() {
    local msg
    local cpu_name
    msg=$1
    cpu_name=$(get_cpu_name)
    [[ -n ${cpu_name} ]] && msg="${msg} [${cpu_name}]"
    echo >&2 "${msg}"
}


## The identified level, as reported to the user.  Level 0 means that
## the CPU does not support x86-64 at all, i.e. there is no such thing
## as an 'x86-64-v0' level
level_label() {
    if [[ $1 -eq 0 ]]; then
        echo "no x86-64 level"
    else
        echo "x86-64-v$1"
    fi
}


## Formats CPU flags as: 'a', or 'a' and 'b', or 'a', 'b', and 'c'
quote_flags() {
    local flag
    local res
    local nbr
    local ii

    nbr=$#
    ii=0
    res=
    for flag in "$@"; do
        ii=$((ii + 1))
        if [[ ${ii} -eq 1 ]]; then
            res="'${flag}'"
        elif [[ ${ii} -lt ${nbr} ]]; then
            res="${res}, '${flag}'"
        elif [[ ${nbr} -eq 2 ]]; then
            res="${res} and '${flag}'"
        else
            res="${res}, and '${flag}'"
        fi
    done
    echo "${res}"
}


has_cpu_flags() {
    local flag
    local missing
    local msg

    missing=()
    for flag; do
        ## Note, it's important to keep a trailing space
        case " ${flags} " in
            *" ${flag} "*)
                :
                ;;
            *)
                missing+=("${flag}")
                ;;
        esac
    done

    [[ ${#missing[@]} -eq 0 ]] && return 0

    if ${verbose}; then
        if [[ ${#missing[@]} -eq 1 ]]; then
            msg="which is not supported by this CPU"
        else
            msg="which are not supported by this CPU"
        fi
        explain "Identified $(level_label "${level}"), because x86-64-v$((level + 1)) requires $(quote_flags "${missing[@]}"), ${msg}"
    fi

    return 1
}


determine_cpu_version() {
    ## No x86-64 support at all, e.g. an i386 or i686 CPU
    level=0

    ## x86-64-v1
    has_cpu_flags lm cmov cx8 fpu fxsr mmx syscall sse2 || return 0
    level=1

    ## x86-64-v2
    has_cpu_flags cx16 lahf_lm popcnt sse4_1 sse4_2 ssse3 || return 0
    level=2

    ## x86-64-v3
    has_cpu_flags avx avx2 bmi1 bmi2 f16c fma abm movbe xsave || return 0
    level=3

    ## x86-64-v4
    has_cpu_flags avx512f avx512bw avx512cd avx512dq avx512vl || return 0
    level=4

    if ${verbose}; then
        explain "Identified x86-64-v${level}, which is the highest x86-64 level"
    fi
}


## Warns if no x86-64 support was identified, although the operating
## system is 64-bit.  Then the CPU flags reported in /proc/cpuinfo must
## be incomplete, which can happen in a virtual machine.  This applies
## only to the current machine, i.e. not when reading from the standard
## input
warn_if_64bit_os() {
    local machine

    ${stdin} && return 0
    [[ ${level} -ne 0 ]] && return 0
    machine=$(uname -m 2> /dev/null)
    [[ ${machine} == "x86_64" ]] || return 0

    echo >&2 "WARNING: The CPU flags in ${cpuinfo} indicate no x86-64 support, although this machine runs a 64-bit operating system ('uname -m' reports '${machine}'), i.e. the reported CPU flags are incomplete, which can happen in a virtual machine"
}


report_cpu_version() {
    read_input
    flags=$(get_cpu_flags) || exit $?
    determine_cpu_version
    warn_if_64bit_os
    echo "${level}"
}


#---------------------------------------------------------------------
# MAIN
#---------------------------------------------------------------------
verbose=false
stdin=false
assert=

# Parse command-line options
while [[ $# -gt 0 ]]; do
    ## Options (--flags):
    if [[ "$1" == "--help" ]]; then
        help
        exit 0
    elif [[ "$1" == "--version" ]]; then
        version
        exit 0
    elif [[ "$1" == "--verbose" ]]; then
        verbose=true
    elif [[ "$1" == "-" ]]; then
        stdin=true
    ## Options (--key=value):
    elif [[ "$1" =~ ^--.*=.*$ ]]; then
        key=${1%%=*}
        key=${key#--}
        value=${1#*=}
        if [[ -z ${value} ]]; then
            echo >&2 "ERROR: Option '--${key}' must not be empty"
            exit 2
        fi
        if [[ "${key}" == "assert" ]]; then
            assert=${value}
            if [[ ! ${assert} =~ ^-?[0-9]+$ ]]; then
                echo >&2 "ERROR: Option --assert does not specify an integer: ${assert}"
                exit 2
            elif [[ ${assert} -lt 1 ]] || [[ ${assert} -gt 4 ]]; then
                echo >&2 "ERROR: Option --assert is out of range [1,4]: ${assert}"
                exit 2
            fi
        else
            echo >&2 "ERROR: Unknown option: $1"
            exit 2
        fi
    else
        echo >&2 "ERROR: Unknown option: $1"
        exit 2
    fi
    shift
done

if [[ -n ${assert} ]]; then
    validate_cpu_flags
    version=$(report_cpu_version) || exit $?
    if [[ ${version} -lt ${assert} ]]; then
        read_input
        cpu_info=$(get_cpu_name)
        [[ -n ${cpu_info} ]] && cpu_info=" [${cpu_info}]"
        >&2 echo "The CPU${cpu_info} on this host ('${HOSTNAME}') supports $(level_label "${version}"), which is less than the required x86-64-v${assert}"
        exit 1
    fi
else
    validate_cpu_flags
    report_cpu_version
fi
